# Generated by Django 4.2.1 on 2023-06-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_remove_film_poster'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='expl_img',
        ),
        migrations.AddField(
            model_name='poster',
            name='film',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='films.film'),
        ),
    ]
