# Generated by Django 4.2.1 on 2023-06-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0002_gif_likes_alter_category_gifs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
