# Generated by Django 4.2.2 on 2023-06-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
