# Generated by Django 4.2.2 on 2023-06-08 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_room_booking_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='check_in_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='check_out_date',
        ),
    ]
