# Generated by Django 4.2.1 on 2023-06-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.ImageField(upload_to='media/posters/'),
        ),
    ]
