# Generated by Django 4.2.1 on 2023-06-05 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('films', '0003_alter_review_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film', to='accounts.poster'),
        ),
    ]
