# Generated by Django 4.2.1 on 2023-06-05 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster',
        ),
    ]
