# Generated by Django 4.2.2 on 2023-06-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_alter_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_field',
            new_name='end_date',
        ),
    ]
