# Generated by Django 4.2.2 on 2023-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0003_rename_end_field_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='admin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
