# Generated by Django 4.2.2 on 2023-06-13 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0005_alter_department_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manage_app.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manage_app.department'),
            preserve_default=False,
        ),
    ]
