# Generated by Django 4.2.2 on 2023-06-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0006_project_department_task_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='department',
        ),
    ]
