# Generated by Django 4.2.2 on 2023-06-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0008_alter_department_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='department',
        ),
    ]
