# Generated by Django 4.2.2 on 2023-06-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_images',
            field=models.IntegerField(default=0),
        ),
    ]
